### ISSUE TITLE
Support magic index variable

### ISSUE THREAD

**Issue by glennlegend** [glennlegend/postcss-for-var-in#1]
It would be nice to have a magic index variable when looping through the vars.

``` css
@forVar $key, $value in @import 'some-vars.css' { 
  .size-$(index) {
    width: $value;
  }
}
```
